# These are supported funding model platforms

github: [rrgeorge] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: rrgeorge
custom:
  - https://rrgeorge.com/support
  - https://marketplace.dndbeyond.com/view/wishlist?id=4e0439d62a7bfbce35a0a6c600
