# These are supported funding model platforms

github: [rrgeorge] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: rrgeorge
custom:
  - https://venmo.com/rrgeorge
  - https://paypal.me/rrgeorge1
