compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - darwin
    - linux
    - win32
  libc:
    - current
    - glibc
    - musl

yarnPath: .yarn/releases/yarn-4.2.1.cjs
